Update ledger-local-setup.md
A custom canister type that uses a .wasm file, according to docs we might not need a build field. But in this case, we'll see an error like this:

Error: Failed to read config from current working directory.
Caused by: Failed to read config from current working directory.
    Failed to read config from directory /Users/me/dev/dfinity/examples/rust/basic_bitcoin.
Failed to load config from /Users/me/dev/dfinity/examples/rust/basic_bitcoin/dfx.json.
  missing field `build` at line 17 column 5

dfx 0.11.1 will make the build field optional again. to fix this, we can add "build": [] to our custom canister definition in dfx.json file.